# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "Boztown/boztown_starter"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "Boztown/boztown_starter"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: 'Dockerfile'
    stage: "build"

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: '${{build}}'
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - bundle exec rails db:migrate
    stage: "test"
    services:
      composition:
        my_postgresql_db:
          image: postgres:latest
          ports:
            - 5432 
      readiness:
        timeoutSeconds: 30
        periodSeconds: 15
        image: 'postgres:latest'
      environment:
        - POSTGRES_DB=db
        - POSTGRES_HOST_AUTH_METHOD=trust

